import { ErrorMessages } from './constants.js';
import type { BaseType } from './types.js';
import { FunctionType, ObjectType } from './types.js';
import { getMemberVarName, isObject, isString } from './utils.js';

export function generate(
  typeObj: BaseType,
  langToLangObj: Map<string, unknown>,
  defaultLang: string,
  global: boolean
): string {
  const languages = [...langToLangObj.keys()].toSorted();

  const varLanguages = 'languages';
  const varCurrentLang = 'currentLang';
  const varI18n = 'i18n';
  const varI18nType = 'I18n';

  let code = `/* eslint-disable */

/*----------------------------------------------------------------------------------------------*
 * You MUST NOT modify this file manually because it is automatically generated by gen-i18n-ts. *
 * Modify your JSON files in i18n directory and run gen-i18n-ts script to regenerate this file. *
 *----------------------------------------------------------------------------------------------*/

`;

  // Generate language union type
  const languageUnion = languages.map((lang) => JSON.stringify(lang)).join(' | ');
  code += `export type SupportedLanguage = ${languageUnion};\n`;
  code += `export const SUPPORTED_LANGUAGES = ${JSON.stringify(languages)} as const;\n`;
  code += `export const DEFAULT_LANGUAGE = ${JSON.stringify(defaultLang)} as const;\n\n`;

  let members = '';
  for (const language of languages) {
    const langCode = langObjToCode(language, langToLangObj.get(language));
    members += `${JSON.stringify(language)}: ${langCode}, `;
  }
  code += `const ${varLanguages} = { ${members} } as const;\n`;

  if (global) {
    code += `let ${varCurrentLang}: typeof ${varLanguages}[SupportedLanguage] = ${varLanguages}[${JSON.stringify(defaultLang)}];\n`;

    const i18nCode = typeObjToCode(typeObj, varCurrentLang);
    code += `export const ${varI18n} = ${i18nCode};\n`;
    code += `export type ${varI18nType} = typeof ${varI18n};\n`;

    code += `${generateChangeLanguageCode(languages, varLanguages, varCurrentLang)}\n`;

    code += `${generateGetLanguageCode()}\n`;
  } else {
    const i18nCode = typeObjToCodeWithLanguageParam(typeObj, varLanguages);
    code += `export const ${varI18n} = ${i18nCode};\n`;
    code += `export type ${varI18nType} = typeof ${varI18n};\n`;
  }

  return code;
}

export function generateNextHelper(i18nImportPath: string, global: boolean): string {
  const i18nImport = global
    ? 'DEFAULT_LANGUAGE, SUPPORTED_LANGUAGES, i18nByCode'
    : 'DEFAULT_LANGUAGE, SUPPORTED_LANGUAGES, i18n';
  const useI18nCode = global
    ? `export function useI18n(): ReturnType<typeof i18nByCode> {
  const locale = useLocaleValue();
  return i18nByCode(locale);
}`
    : `export function useI18n(): ReturnType<typeof i18n> {
  const locale = useLocaleValue();
  return i18n(locale);
}`;

  return `/* eslint-disable */

/*----------------------------------------------------------------------------------------------*
 * You MUST NOT modify this file manually because it is automatically generated by gen-i18n-ts. *
 * Modify your JSON files in i18n directory and run gen-i18n-ts script to regenerate this file. *
 *----------------------------------------------------------------------------------------------*/

'use client';

import { useParams, usePathname, useRouter } from 'next/navigation';
import type React from 'react';
import { createContext, useContext, useEffect, useState } from 'react';

import { ${i18nImport} } from ${JSON.stringify(i18nImportPath)};
import type { SupportedLanguage } from ${JSON.stringify(i18nImportPath)};

interface LocaleContextValue {
  locale: SupportedLanguage;
  setLocale: (locale: string) => boolean;
}

interface LocaleProviderProps {
  children: React.ReactNode;
}

const LocaleContext = createContext<LocaleContextValue | undefined>(undefined);

export const LOCALE_COOKIE_NAME = 'preferred-locale';
const LOCALE_COOKIE_MAX_AGE_SECONDS = 60 * 60 * 24 * 365;

export const LocaleProvider: React.FC<LocaleProviderProps> = ({ children }) => {
  const params = useParams<{ locale?: string | string[] }>();
  const pathname = usePathname();
  const router = useRouter();

  const routeLocale = Array.isArray(params.locale) ? params.locale[0] : params.locale;
  const [detectedLocale, setDetectedLocale] = useState<SupportedLanguage | undefined>();
  const locale = isSupportedLanguage(routeLocale) ? routeLocale : detectedLocale ?? DEFAULT_LANGUAGE;
  useEffect(() => {
    if (isSupportedLanguage(routeLocale)) return;
    setDetectedLocale(detectLocaleFromBrowser());
  }, [routeLocale]);

  const setLocale = (newLocale: string): boolean => {
    if (!isSupportedLanguage(newLocale)) {
      console.warn(\`Locale "\${newLocale}" is not supported. Supported locales:\`, SUPPORTED_LANGUAGES);
      return false;
    }

    setLocalePreference(newLocale);
    const nextPathname = replaceLocaleSegment(pathname, locale, newLocale);
    const query = getCurrentSearchParams();
    const hash = getCurrentHash();
    router.push(\`\${nextPathname}\${query ? \`?\${query}\` : ''}\${hash}\`);
    return true;
  };

  return <LocaleContext.Provider value={{ locale, setLocale }}>{children}</LocaleContext.Provider>;
};

${useI18nCode}

export function useLocaleValue(): SupportedLanguage {
  return useLocaleContext().locale;
}

export function useSetLocale(): (locale: string) => boolean {
  return useLocaleContext().setLocale;
}

function useLocaleContext(): LocaleContextValue {
  const context = useContext(LocaleContext);
  if (!context) throw new Error('LocaleProvider is missing.');
  return context;
}

function isSupportedLanguage(locale: string | undefined): locale is SupportedLanguage {
  return SUPPORTED_LANGUAGES.includes(locale as SupportedLanguage);
}

function detectLocaleFromBrowser(): SupportedLanguage {
  if (!('window' in globalThis)) return DEFAULT_LANGUAGE;

  try {
    const storedLocale =
      localStorage.getItem(LOCALE_COOKIE_NAME) ||
      document.cookie
        .split('; ')
        .find((row) => row.startsWith(\`\${LOCALE_COOKIE_NAME}=\`))
        ?.split('=')[1];
    if (isSupportedLanguage(storedLocale)) return storedLocale;
  } catch {
    // Storage may be unavailable even when navigator.language is still usable.
  }

  const browserLanguage = navigator.language;
  if (isSupportedLanguage(browserLanguage)) return browserLanguage;

  const languagePrefix = browserLanguage.split('-')[0];
  const matchingLocale = SUPPORTED_LANGUAGES.find((supportedLanguage) => {
    return !!languagePrefix && supportedLanguage.startsWith(languagePrefix);
  });
  return matchingLocale ?? DEFAULT_LANGUAGE;
}

function setLocalePreference(locale: SupportedLanguage): void {
  if (!('window' in globalThis)) return;

  try {
    localStorage.setItem(LOCALE_COOKIE_NAME, locale);
    document.cookie = \`\${LOCALE_COOKIE_NAME}=\${locale}; max-age=\${LOCALE_COOKIE_MAX_AGE_SECONDS}; path=/; SameSite=Lax\`;
  } catch {
    return;
  }
}

function getCurrentSearchParams(): string {
  if (!('window' in globalThis)) return '';
  return globalThis.location.search.replace(/^\\?/, '');
}

function getCurrentHash(): string {
  if (!('window' in globalThis)) return '';
  return globalThis.location.hash;
}

function replaceLocaleSegment(pathname: string, currentLocale: SupportedLanguage, nextLocale: SupportedLanguage): string {
  const segments = pathname.split('/');
  if (segments[1] === currentLocale || isSupportedLanguage(segments[1])) {
    segments[1] = nextLocale;
    return segments.join('/') || '/';
  }
  return \`/\${nextLocale}\${pathname}\`;
}
`;
}

export function generateNextServerHelper(i18nImportPath: string): string {
  return `/* eslint-disable */

/*----------------------------------------------------------------------------------------------*
 * You MUST NOT modify this file manually because it is automatically generated by gen-i18n-ts. *
 * Modify your JSON files in i18n directory and run gen-i18n-ts script to regenerate this file. *
 *----------------------------------------------------------------------------------------------*/

import 'server-only';

import { cookies, headers } from 'next/headers';
import type { NextRequest } from 'next/server';

import { DEFAULT_LANGUAGE, SUPPORTED_LANGUAGES, i18n } from ${JSON.stringify(i18nImportPath)};
import type { SupportedLanguage } from ${JSON.stringify(i18nImportPath)};

export const LOCALE_COOKIE_NAME = 'preferred-locale';

export async function getI18n(): Promise<ReturnType<typeof i18n>> {
  return i18n(await getServerSideLocale());
}

export async function getServerSideLocale(): Promise<SupportedLanguage> {
  const cookieLocale = await getLocaleFromCookies();
  if (cookieLocale) return cookieLocale;

  const headersList = await headers();
  return getLocaleFromAcceptLanguage(headersList.get('accept-language'));
}

export async function getLocaleFromCookies(): Promise<SupportedLanguage | undefined> {
  const cookieStore = await cookies();
  return getSupportedLanguage(cookieStore.get(LOCALE_COOKIE_NAME)?.value);
}

export function getLocaleFromNextRequest(request: NextRequest): SupportedLanguage {
  const cookieLocale = getSupportedLanguage(request.cookies.get(LOCALE_COOKIE_NAME)?.value);
  if (cookieLocale) return cookieLocale;

  return getLocaleFromAcceptLanguage(request.headers.get('accept-language'));
}

export function getLocaleFromAcceptLanguage(acceptLanguage: string | null | undefined): SupportedLanguage {
  for (const language of getLanguagesFromAcceptLanguage(acceptLanguage)) {
    const exactMatch = getSupportedLanguage(language);
    if (exactMatch) return exactMatch;

    const languagePrefix = language.split('-')[0];
    const prefixMatch = SUPPORTED_LANGUAGES.find((supportedLanguage) => {
      return !!languagePrefix && supportedLanguage.startsWith(languagePrefix);
    });
    if (prefixMatch) return prefixMatch;
  }

  return DEFAULT_LANGUAGE;
}

function getLanguagesFromAcceptLanguage(acceptLanguage: string | null | undefined): string[] {
  if (!acceptLanguage) return [];

  return acceptLanguage
    .split(',')
    .map((language) => language.split(';')[0]?.trim())
    .filter((language): language is string => !!language && language !== '*' && isValidLocaleCandidate(language));
}

function getSupportedLanguage(language: string | undefined): SupportedLanguage | undefined {
  if (!language) return undefined;
  return SUPPORTED_LANGUAGES.includes(language as SupportedLanguage) ? (language as SupportedLanguage) : undefined;
}

function isValidLocaleCandidate(language: string): boolean {
  try {
    return Intl.getCanonicalLocales(language).length > 0;
  } catch {
    return false;
  }
}
`;
}

function langObjToCode(lang: string, langObj: unknown): string {
  if (!isObject(langObj)) throw new Error(ErrorMessages.langFileNotObject(lang));

  return langObjToCodeRecursively(lang, langObj, '');
}

function langObjToCodeRecursively(lang: string, langObj: unknown, varName: string): string {
  if (isString(langObj)) {
    return JSON.stringify(langObj);
  } else if (isObject(langObj)) {
    let members = '';
    for (const [key, value] of Object.entries(langObj)) {
      const memberVarName = getMemberVarName(varName, key);
      const valueCode = langObjToCodeRecursively(lang, value, memberVarName);
      members += `${JSON.stringify(key)}: ${valueCode}, `;
    }
    return `{ "__code__": "${lang}", ${members} }`;
  }

  throw new Error(ErrorMessages.varShouldStringOrObject(lang, varName));
}

function typeObjToCodeWithLanguageParam(typeObj: BaseType, varLanguages: string): string {
  const varLanguage = 'language';
  const varCurrentLang = 'currentLang';

  let code = `function (${varLanguage}: string) {\n`;
  code += `  if (!(${varLanguage} in ${varLanguages})) throw new Error(\`Language "\${${varLanguage}}" not found\`);\n`;
  code += `  const ${varCurrentLang} = ${varLanguages}[${varLanguage} as SupportedLanguage];\n`;

  const i18nCode = typeObjToCode(typeObj, varCurrentLang);
  code += `  return ${i18nCode};\n`;
  code += `}`;

  return code;
}

function typeObjToCode(typeObj: BaseType, varName: string): string {
  if (typeObj instanceof FunctionType) {
    if (typeObj.params.length === 0) {
      const declaration = `function (): string`;
      return `${declaration} { return ${varName} }`;
    }

    const paramTypes = typeObj.params.map((param) => `${param}: unknown`).join(', ');
    const paramDestructure = `{ ${typeObj.params.join(', ')} }`;
    const declaration = `function (${paramDestructure}: { ${paramTypes} }): string`;

    const varParamMap = 'paramMap';
    const members = typeObj.params.map((param) => `"\${${param}}" : String(${param}),`).join(' ');
    const declarationStatement = `const ${varParamMap}: Record<string, string> = { ${members} };`;

    const varPattern = 'pattern';
    const patterns = typeObj.params.map((param) => String.raw`\$\{${param}\}`).join('|');
    const regex = `/${patterns}/g`;
    const replaceFunc = `(${varPattern}) => ${varParamMap}[${varPattern}] ?? ''`;
    const returnStatement = `return ${varName}.replaceAll(${regex}, ${replaceFunc});`;

    return `${declaration} { ${declarationStatement} ${returnStatement} }`;
  } else if (typeObj instanceof ObjectType) {
    let members = '';
    for (const [key, value] of Object.entries(typeObj.map)) {
      const memberVarName = getMemberVarName(varName, key);
      const valueCode = typeObjToCode(value, memberVarName);
      members += `${JSON.stringify(key)}: ${valueCode}, `;
    }
    return `{ ${members} }`;
  } else {
    throw new TypeError(ErrorMessages.unreachable());
  }
}

function generateChangeLanguageCode(langs: string[], varLanguages: string, varCurrentLang: string): string {
  const funcChangeCurrentLang = 'changeLanguageByCode';
  const varLang = 'lang';
  const declaration = `export function ${funcChangeCurrentLang}(${varLang}: SupportedLanguage): true;\nexport function ${funcChangeCurrentLang}(${varLang}: string): boolean;\nexport function ${funcChangeCurrentLang}(${varLang}: string): boolean`;

  const cases = langs
    .map((lang) => `case "${lang}": ${varCurrentLang} = ${varLanguages}[${JSON.stringify(lang)}]; return true;`)
    .join(' ');
  const statement = `switch (${varLang}) { ${cases} } return false;`;

  return `${declaration} { ${statement} }`;
}

function generateGetLanguageCode(): string {
  return `export function getCurrentLanguageCode(): string {
  return currentLang.__code__;
}
export function getFullAndShortLanguageCodeList(): string[] {
  const langSet = new Set<string>();
  const fullLangs = getFullLanguageCodeList();
  const shortLangs = getShortLanguageCodeList();
  const length = Math.max(fullLangs.length, shortLangs.length);
  for (let i = 0; i < length; i++) {
    const fullLang = fullLangs[i];
    if (fullLang) langSet.add(fullLang);
    const shortLang = shortLangs[i];
    if (shortLang) langSet.add(shortLang);
  }
  return [...langSet];
}
export function getFullLanguageCodeList(): string[] {
  const langSet = new Set<string>();
  const nav = window.navigator || {};
  if (Array.isArray(nav.languages)) {
    for (const lang of nav.languages) {
      if (lang) langSet.add(lang);
    }
  }
  for (const key of ['language', 'browserLanguage', 'systemLanguage', 'userLanguage']) {
    const lang = (nav as any)[key];
    if (lang) langSet.add(lang);
  }
  return [...langSet];
}
export function getShortLanguageCodeList(): string[] {
  return [...new Set(getFullLanguageCodeList().map(lang => lang.split('-')[0] ?? '').filter(lang => !!lang))];
}
export function i18nByCode(langCode: string): typeof i18n {
  changeLanguageByCode(langCode);
  return i18n;
}`;
}
