name: autofix.ci
on:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: read
concurrency:
  group: autofix-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  autofix:
    runs-on: ubuntu-latest
    env:
      WB_ENV: development
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4.2.0
        with:
          cache: true
      - run: bun install
      - run: bun run cleanup
      - run: bun run build
      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a
