name: Test

on:
  pull_request:
    branches:
      - '**'
      - '!renovate/**'
  push:
    branches:
      - 'main'
      - 'renovate/**'
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Show environment information
        run: |
          echo "node: $(node -v)"
          echo "yarn: $(yarn -v)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: .yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install
      # Generate ts files required in type-checking and linting
      - run: yarn test
      - run: yarn typecheck
      - run: yarn lint
